// <auto-generated by MimesisSeedScanner — do not edit>
#nullable disable
// Run scripts/generate-dungeon-seeds.sh after in-game scan to populate pools.

namespace MimesisPlayerEnhancement.Features.DungeonRandomizer
{
    internal static partial class DungeonSeedPools
    {
        internal static ReadOnlySpan<int> GetPool(string flowId, DungeonSeedFlavor flavor)
        {
            if (flavor == DungeonSeedFlavor.Vanilla)
            {
                return ReadOnlySpan<int>.Empty;
            }

            return TryGetPool(flowId, flavor, out int[] pool) ? pool : ReadOnlySpan<int>.Empty;
        }

        private static bool TryGetPool(string flowId, DungeonSeedFlavor flavor, out int[] pool)
        {
            pool = null;
            return false;
        }
    }
}
