#!/usr/bin/env bash
# Build the Web Dashboard Svelte app via Docker and embed output into the mod assets folder.
# Requires Docker (daemon running). No local Node.js needed.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
WEB_SRC="$ROOT/src/MimesisPlayerEnhancementWeb"
OUT_DIR="$ROOT/src/MimesisPlayerEnhancement/Assets/WebDashboard"
TMP_DIR="$ROOT/.tmp-webdashboard"

if ! command -v docker >/dev/null 2>&1; then
  echo "error: docker is required to build the web dashboard" >&2
  exit 1
fi

if [[ ! -f "$WEB_SRC/package.json" ]]; then
  echo "error: missing $WEB_SRC/package.json" >&2
  exit 1
fi

echo "Building web dashboard (Docker)…"
docker build -t mpe-webdashboard:local -f "$WEB_SRC/Dockerfile" "$WEB_SRC"

mkdir -p "$OUT_DIR" "$TMP_DIR"
# Preserve static images shipped with the mod (not generated by Vite).
for asset in default-avatar.svg bg-placeholder.svg logo.png favicon.ico favicon.png; do
  if [[ -f "$OUT_DIR/img/$asset" ]]; then
    cp "$OUT_DIR/img/$asset" "$TMP_DIR/$asset"
  fi
done

docker run --rm \
  --user "$(id -u):$(id -g)" \
  -v "$OUT_DIR:/out" \
  mpe-webdashboard:local

mkdir -p "$OUT_DIR/img"
for asset in default-avatar.svg bg-placeholder.svg logo.png favicon.ico favicon.png; do
  if [[ -f "$TMP_DIR/$asset" ]]; then
    cp "$TMP_DIR/$asset" "$OUT_DIR/img/$asset"
  fi
done
rm -rf "$TMP_DIR"

if [[ ! -f "$OUT_DIR/index.html" ]]; then
  echo "error: build did not produce $OUT_DIR/index.html" >&2
  exit 1
fi

echo "Web dashboard built → $OUT_DIR"
