using System.Globalization;
using System.Text;

namespace MimesisSeedScanner
{
    public static class SeedPoolCodeGenerator
    {
        private static readonly HashSet<string> CuratedFlavors = new(CuratedFlavorNames.All, StringComparer.Ordinal);

        public static string Generate(SeedScanDocument document)
        {
            var builder = new StringBuilder();
            builder.AppendLine("// <auto-generated by MimesisSeedScanner — do not edit>");
            builder.AppendLine("#nullable disable");
            builder.AppendLine("// Run scripts/generate-dungeon-seeds.sh after CLI scan to populate pools.");
            builder.AppendLine();
            builder.AppendLine("namespace MimesisPlayerEnhancement.Features.DungeonRandomizer");
            builder.AppendLine("{");
            builder.AppendLine("    internal static partial class DungeonSeedPools");
            builder.AppendLine("    {");
            builder.AppendLine("        internal static ReadOnlySpan<int> GetPool(string flowId, DungeonSeedFlavor flavor)");
            builder.AppendLine("        {");
            builder.AppendLine("            if (flavor == DungeonSeedFlavor.Vanilla)");
            builder.AppendLine("            {");
            builder.AppendLine("                return ReadOnlySpan<int>.Empty;");
            builder.AppendLine("            }");
            builder.AppendLine();
            builder.AppendLine("            return TryGetPool(flowId, flavor, out int[] pool) ? pool : ReadOnlySpan<int>.Empty;");
            builder.AppendLine("        }");
            builder.AppendLine();
            builder.AppendLine("        private static bool TryGetPool(string flowId, DungeonSeedFlavor flavor, out int[] pool)");
            builder.AppendLine("        {");
            builder.AppendLine("            switch (flowId, flavor)");
            builder.AppendLine("            {");

            int caseCount = 0;
            foreach (FlowSeedScanResult flow in document.Flows)
            {
                foreach (FlavorSeedScanResult flavorResult in flow.Flavors)
                {
                    if (flavorResult.Seeds.Count == 0)
                    {
                        continue;
                    }

                    if (!CuratedFlavors.Contains(flavorResult.Flavor))
                    {
                        continue;
                    }

                    string seeds = string.Join(", ", flavorResult.Seeds.Select(seed => seed.ToString(CultureInfo.InvariantCulture)));
                    builder.Append("                case (\"")
                        .Append(Escape(flow.FlowId))
                        .Append("\", DungeonSeedFlavor.")
                        .Append(flavorResult.Flavor)
                        .Append("):\n                    pool = new[] { ")
                        .Append(seeds)
                        .AppendLine(" };");
                    builder.AppendLine("                    return true;");
                    caseCount++;
                }
            }

            builder.AppendLine("                default:");
            builder.AppendLine("                    pool = null;");
            builder.AppendLine("                    return false;");
            builder.AppendLine("            }");
            builder.AppendLine("        }");
            builder.AppendLine("    }");
            builder.AppendLine("}");

            if (caseCount == 0)
            {
                builder.AppendLine();
                builder.AppendLine("// No seed pools were emitted — run the in-game scanner and re-run codegen.");
            }

            return builder.ToString();
        }

        private static string Escape(string value) => value.Replace("\\", "\\\\", StringComparison.Ordinal).Replace("\"", "\\\"", StringComparison.Ordinal);
    }
}
