using MimesisPlayerEnhancement.Util;

namespace MimesisPlayerEnhancement.Tests.Features.SpawnScaling
{
    internal static class SpawnScalingSceneConfigTestFactory
    {
        internal static SpawnScalingSceneConfig Create(
            bool enableSpawnScaling = true,
            int spawnScalingBaselinePlayerCount = ScalingMath.VanillaPlayerBaseline,
            float mimicSpawnMultiplier = 1f,
            float mimicSpawnPerPlayerMultiplier = ScalingMath.DefaultPerPlayerMultiplier,
            string mimicWaveMode = "Vanilla",
            float mimicWaveInitialDelaySeconds = 60f,
            float mimicWaveInitialDelayMinSeconds = 30f,
            float mimicWaveInitialDelayMaxSeconds = 90f,
            float mimicWaveIntervalSeconds = 30f,
            float mimicWaveIntervalMinSeconds = 20f,
            float mimicWaveIntervalMaxSeconds = 45f,
            float bossSpawnMultiplier = 1f,
            float bossSpawnPerPlayerMultiplier = ScalingMath.DefaultPerPlayerMultiplier,
            float gruntSpawnMultiplier = 1f,
            float gruntSpawnPerPlayerMultiplier = ScalingMath.DefaultPerPlayerMultiplier,
            string gruntWaveMode = "Vanilla",
            float gruntWaveInitialDelaySeconds = 60f,
            float gruntWaveInitialDelayMinSeconds = 30f,
            float gruntWaveInitialDelayMaxSeconds = 90f,
            float gruntWaveIntervalSeconds = 30f,
            float gruntWaveIntervalMinSeconds = 20f,
            float gruntWaveIntervalMaxSeconds = 45f,
            float specialSpawnMultiplier = 1f,
            float specialSpawnPerPlayerMultiplier = ScalingMath.DefaultPerPlayerMultiplier,
            float trapSpawnMultiplier = 1f,
            float trapSpawnPerPlayerMultiplier = ScalingMath.DefaultPerPlayerMultiplier,
            string trapRespawnMode = "Vanilla",
            float trapRespawnDelaySeconds = 5f,
            float trapRespawnDelayMinSeconds = 5f,
            float trapRespawnDelayMaxSeconds = 30f,
            float trapRespawnMinPlayerDistanceMeters = 10f,
            float otherSpawnMultiplier = 1f,
            float otherSpawnPerPlayerMultiplier = ScalingMath.DefaultPerPlayerMultiplier,
            float bonusEncounterDelayMinSeconds = 5f,
            float bonusEncounterDelayMaxSeconds = 30f,
            float bonusEncounterMinPlayerDistanceMeters = 10f) =>
            new(
                enableSpawnScaling,
                spawnScalingBaselinePlayerCount,
                mimicSpawnMultiplier,
                mimicSpawnPerPlayerMultiplier,
                mimicWaveMode,
                mimicWaveInitialDelaySeconds,
                mimicWaveInitialDelayMinSeconds,
                mimicWaveInitialDelayMaxSeconds,
                mimicWaveIntervalSeconds,
                mimicWaveIntervalMinSeconds,
                mimicWaveIntervalMaxSeconds,
                bossSpawnMultiplier,
                bossSpawnPerPlayerMultiplier,
                gruntSpawnMultiplier,
                gruntSpawnPerPlayerMultiplier,
                gruntWaveMode,
                gruntWaveInitialDelaySeconds,
                gruntWaveInitialDelayMinSeconds,
                gruntWaveInitialDelayMaxSeconds,
                gruntWaveIntervalSeconds,
                gruntWaveIntervalMinSeconds,
                gruntWaveIntervalMaxSeconds,
                specialSpawnMultiplier,
                specialSpawnPerPlayerMultiplier,
                trapSpawnMultiplier,
                trapSpawnPerPlayerMultiplier,
                trapRespawnMode,
                trapRespawnDelaySeconds,
                trapRespawnDelayMinSeconds,
                trapRespawnDelayMaxSeconds,
                trapRespawnMinPlayerDistanceMeters,
                otherSpawnMultiplier,
                otherSpawnPerPlayerMultiplier,
                bonusEncounterDelayMinSeconds,
                bonusEncounterDelayMaxSeconds,
                bonusEncounterMinPlayerDistanceMeters);
    }
}
